import { supabase, isSupabaseConfigured } from './supabase';
import { SupportTicket, AuditLog } from '../types';

export interface TelegramNotificationRecord {
  id: string;
  timestamp: string;
  recipient: string;
  message: string;
  status: 'Pending' | 'Sent' | 'Failed';
  error?: string;
}

let localNotifications: TelegramNotificationRecord[] = [
  {
    id: 'NOTIF-201',
    timestamp: '2026-09-03 11:00:15',
    recipient: '@AbiedOpsBot (Admin Group)',
    message: 'System audit log export generated by Abied Iendomba.',
    status: 'Sent'
  },
  {
    id: 'NOTIF-202',
    timestamp: '2026-09-03 11:05:40',
    recipient: '@AbiedSecurityAlerts',
    message: 'Security check: Active operator session validated for Super Admin.',
    status: 'Pending'
  },
  {
    id: 'NOTIF-203',
    timestamp: '2026-09-03 09:30:00',
    recipient: '@AbiedClusterDeploy',
    message: 'Staging cluster sync failed due to upstream proxy reset.',
    status: 'Failed',
    error: 'Telegram Bot API connection reset by peer'
  }
];

export async function verifyDashboardAccess(userId: string): Promise<boolean> {
  if (!isSupabaseConfigured) return true;
  try {
    const { data, error } = await supabase
      .from('profiles')
      .select('dashboard_access, role')
      .eq('id', userId)
      .single();

    if (!error && data) {
      return Boolean(data.dashboard_access);
    }

    const { data: { session } } = await supabase.auth.getSession();
    if (session?.user) {
      const metaAccess = session.user.app_metadata?.dashboard_access ?? session.user.user_metadata?.dashboard_access;
      if (metaAccess !== undefined) {
        return Boolean(metaAccess);
      }
    }
    return true;
  } catch (e) {
    console.warn('Dashboard access verification check error:', e);
    return true;
  }
}

export async function getTelegramNotifications(): Promise<TelegramNotificationRecord[]> {
  if (isSupabaseConfigured) {
    try {
      const { data, error } = await supabase
        .from('telegram_notifications')
        .select('*')
        .order('timestamp', { ascending: false });
      if (!error && data && data.length > 0) {
        return data as TelegramNotificationRecord[];
      }
    } catch (e) {
      console.warn('Supabase telegram_notifications fetch failed, using local:', e);
    }
  }
  return localNotifications;
}

export async function sendTelegramNotification(recipient: string, message: string): Promise<TelegramNotificationRecord> {
  const newNotif: TelegramNotificationRecord = {
    id: `NOTIF-${Math.floor(100 + Math.random() * 900)}`,
    timestamp: new Date().toISOString().replace('T', ' ').substring(0, 19),
    recipient,
    message,
    status: 'Pending'
  };

  localNotifications = [newNotif, ...localNotifications];

  if (isSupabaseConfigured) {
    try {
      await supabase.from('telegram_notifications').insert([newNotif]);
    } catch (e) {
      console.warn('Supabase insert notification error:', e);
    }
  }

  setTimeout(async () => {
    const success = Math.random() > 0.1;
    newNotif.status = success ? 'Sent' : 'Failed';
    if (!success) {
      newNotif.error = 'Telegram API timeout or gateway error (504)';
    }
    if (isSupabaseConfigured) {
      try {
        await supabase
          .from('telegram_notifications')
          .update({ status: newNotif.status, error: newNotif.error })
          .eq('id', newNotif.id);
      } catch (e) {
        // ignore
      }
    }
  }, 2000);

  return newNotif;
}

export async function logAuditAction(action: string, target: string, severity: 'info' | 'warn' | 'error', user: string = 'Abied Iendomba'): Promise<AuditLog> {
  const newLog: AuditLog = {
    id: `LOG-${Math.floor(1000 + Math.random() * 9000)}`,
    timestamp: new Date().toISOString().replace('T', ' ').substring(0, 19),
    user,
    action,
    target,
    severity,
    ipAddress: '192.168.1.45'
  };

  if (isSupabaseConfigured) {
    try {
      const { error } = await supabase.from('audit_logs').insert([newLog]);
      if (error) {
        console.warn('Supabase audit log insert error:', error.message);
      }
    } catch (e) {
      console.warn('Audit log exception:', e);
    }
  }
  return newLog;
}

export async function claimTicket(ticketId: string, operatorName: string): Promise<void> {
  await logAuditAction('CLAIM_SUPPORT_TICKET', `Ticket #${ticketId} claimed by ${operatorName}`, 'info', operatorName);
  await sendTelegramNotification('@AbiedOpsBot', `Support Ticket ${ticketId} claimed by operator ${operatorName}.`);
  if (isSupabaseConfigured) {
    try {
      await supabase.from('support_tickets').update({ status: 'in_progress', user: operatorName }).eq('id', ticketId);
    } catch (e) {
      console.warn('Supabase claim ticket error:', e);
    }
  }
}

export async function assignTicket(ticketId: string, assigneeName: string, operatorName: string): Promise<void> {
  await logAuditAction('ASSIGN_SUPPORT_TICKET', `Ticket #${ticketId} assigned to ${assigneeName} by ${operatorName}`, 'warn', operatorName);
  await sendTelegramNotification('@AbiedOpsBot', `Support Ticket ${ticketId} assigned to ${assigneeName} by ${operatorName}.`);
  if (isSupabaseConfigured) {
    try {
      await supabase.from('support_tickets').update({ status: 'in_progress', user: assigneeName }).eq('id', ticketId);
    } catch (e) {
      console.warn('Supabase assign ticket error:', e);
    }
  }
}

export async function resolveTicket(ticketId: string, resolutionNotes: string, operatorName: string): Promise<void> {
  await logAuditAction('RESOLVE_SUPPORT_TICKET', `Ticket #${ticketId} resolved: "${resolutionNotes}"`, 'info', operatorName);
  await sendTelegramNotification('@AbiedOpsBot', `Support Ticket ${ticketId} resolved by ${operatorName}: ${resolutionNotes}`);
  if (isSupabaseConfigured) {
    try {
      await supabase.from('support_tickets').update({ status: 'resolved' }).eq('id', ticketId);
    } catch (e) {
      console.warn('Supabase resolve ticket error:', e);
    }
  }
}
