import { supabase, isSupabaseConfigured } from './supabase';
import { SupportTicket, AuditLog } from '../types';

export interface TelegramNotificationRecord {
  id: string;
  timestamp: string;
  recipient: string;
  message: string;
  status: 'Pending' | 'Sent' | 'Failed';
  channelType?: 'admin_private' | 'member_group';
  error?: string;
}

export interface EmergencyActionPayload {
  actionType: 'freeze_payments' | 'cloudflare_lockdown' | 'revoke_sessions' | 'panic_broadcast' | 'maintenance_toggle';
  reason: string;
  operator: string;
  scope?: string;
}

let localNotifications: TelegramNotificationRecord[] = [
  {
    id: 'NOTIF-201',
    timestamp: '2026-09-06 20:00:15',
    recipient: '@sandekalabot (Admin Ops Channel)',
    message: 'System audit log export generated by Super Admin.',
    channelType: 'admin_private',
    status: 'Sent'
  },
  {
    id: 'NOTIF-202',
    timestamp: '2026-09-06 20:15:40',
    recipient: '@mrssandebot (Member Group: t.me/+ybOzZ_lstEdhNDU1)',
    message: '🎉 Notifikasi Gaji: Batch klaim member #104 telah diverifikasi.',
    channelType: 'member_group',
    status: 'Sent'
  }
];

export async function verifyDashboardAccess(userId: string): Promise<boolean> {
  if (!isSupabaseConfigured) return true;
  try {
    const { data, error } = await supabase
      .from('profiles')
      .select('dashboard_access, role')
      .eq('id', userId)
      .single();

    if (!error && data) {
      return Boolean(data.dashboard_access);
    }

    const { data: { session } } = await supabase.auth.getSession();
    if (session?.user) {
      const metaAccess = session.user.app_metadata?.dashboard_access ?? session.user.user_metadata?.dashboard_access;
      if (metaAccess !== undefined) {
        return Boolean(metaAccess);
      }
    }
    return true;
  } catch (e) {
    console.warn('Dashboard access verification check error:', e);
    return true;
  }
}

export interface TelegramAuthPayload {
  id: number;
  first_name: string;
  last_name?: string;
  username?: string;
  photo_url?: string;
  auth_date: number;
  hash: string;
}

export async function loginWithTelegram(telegramPayload: TelegramAuthPayload): Promise<{ magic_link: string; email: string }> {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  if (!supabaseUrl) throw new Error('Supabase URL not configured');

  const functionUrl = `${supabaseUrl}/functions/v1/telegram-auth`;
  const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

  const response = await fetch(functionUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': anonKey,
      'Authorization': `Bearer ${anonKey}`,
    },
    body: JSON.stringify({ telegramPayload }),
  });

  const result = await response.json();
  if (!response.ok) {
    throw new Error(result.error || 'Telegram authentication failed');
  }
  return result;
}

export async function getTelegramNotifications(): Promise<TelegramNotificationRecord[]> {
  if (isSupabaseConfigured) {
    try {
      const { data, error } = await supabase
        .from('telegram_notifications')
        .select('*')
        .order('timestamp', { ascending: false });
      if (!error && data && data.length > 0) {
        return data as TelegramNotificationRecord[];
      }
    } catch (e) {
      console.warn('Supabase telegram_notifications fetch failed, using local:', e);
    }
  }
  return localNotifications;
}

export async function sendTelegramNotification(
  recipient: string, 
  message: string, 
  channelType: 'admin_private' | 'member_group' = 'admin_private'
): Promise<TelegramNotificationRecord> {
  const newNotif: TelegramNotificationRecord = {
    id: `NOTIF-${Math.floor(100 + Math.random() * 900)}`,
    timestamp: new Date().toISOString().replace('T', ' ').substring(0, 19),
    recipient,
    message,
    channelType,
    status: 'Pending'
  };

  localNotifications = [newNotif, ...localNotifications];

  if (isSupabaseConfigured) {
    try {
      await supabase.from('telegram_notifications').insert([newNotif]);
    } catch (e) {
      console.warn('Supabase insert notification error:', e);
    }
  }

  setTimeout(async () => {
    newNotif.status = 'Sent';
    if (isSupabaseConfigured) {
      try {
        await supabase
          .from('telegram_notifications')
          .update({ status: 'Sent' })
          .eq('id', newNotif.id);
      } catch (e) {
        // ignore
      }
    }
  }, 1000);

  return newNotif;
}

/**
 * Notifikasi Pembayaran Terverifikasi:
 * 1. Kirim rincian rahasia & audit ke Admin/Dev (@sandekalabot)
 * 2. Kirim notifikasi publik yang aman ke Grup Member (@mrssandebot)
 */
export async function sendPaymentVerifiedNotification(
  paymentId: string | number,
  userId: string | number,
  amount: number | string,
  operatorName: string
): Promise<void> {
  // 1. Notifikasi Admin / Dev (Detail Finansial)
  const adminMessage = `💳 [PAYROLL VERIFIED] Pembayaran #${paymentId} untuk User ID #${userId} senilai Rp ${amount} telah DISETUJUI oleh ${operatorName}.`;
  await sendTelegramNotification('@sandekalabot (Admin & Dev Channel)', adminMessage, 'admin_private');

  // 2. Notifikasi Member Group (Aman & Transparan via @mrssandebot)
  const memberGroupMessage = `🎉 [KLAIM GAJI SUKSES] Pembayaran untuk Member ID #${userId} telah berhasil diverifikasi oleh Tim Finance & Admin. Saldo / transfer telah diproses. Terima kasih atas kerja keras Anda! 🚀\nGroup: https://t.me/+ybOzZ_lstEdhNDU1`;
  await sendTelegramNotification('@mrssandebot (Grup Member Komunitas)', memberGroupMessage, 'member_group');

  await logAuditAction('VERIFY_PAYMENT_PAYROLL', `Payment #${paymentId} approved by ${operatorName}`, 'info', operatorName);
}

export async function logAuditAction(
  action: string, 
  target: string, 
  severity: 'info' | 'warn' | 'error', 
  user: string = 'Abied Iendomba'
): Promise<AuditLog> {
  const newLog: AuditLog = {
    id: `LOG-${Math.floor(1000 + Math.random() * 9000)}`,
    timestamp: new Date().toISOString().replace('T', ' ').substring(0, 19),
    user,
    action,
    target,
    severity,
    ipAddress: '192.168.1.45'
  };

  if (isSupabaseConfigured) {
    try {
      const { error } = await supabase.from('audit_logs').insert([newLog]);
      if (error) {
        console.warn('Supabase audit log insert error:', error.message);
      }
    } catch (e) {
      console.warn('Audit log exception:', e);
    }
  }
  return newLog;
}

/**
 * Menu Instan / Emergency Action (Incident & Safety Control)
 */
export async function executeEmergencyAction(payload: EmergencyActionPayload): Promise<{ success: boolean; message: string }> {
  const { actionType, reason, operator } = payload;
  
  await logAuditAction(
    `EMERGENCY_${actionType.toUpperCase()}`, 
    `Reason: ${reason} (Initiated by ${operator})`, 
    'error', 
    operator
  );

  let alertMessage = '';
  switch (actionType) {
    case 'freeze_payments':
      alertMessage = `🚨 [EMERGENCY FREEZE] Semua proses pembayaran & payout DIBEKUKAN sementara oleh ${operator}. Alasan: ${reason}`;
      break;
    case 'cloudflare_lockdown':
      alertMessage = `🛡️ [UNDER ATTACK MODE] Cloudflare & DNS Lockdown diaktifkan oleh ${operator}. Proteksi DDoS I'm Under Attack aktif.`;
      break;
    case 'revoke_sessions':
      alertMessage = `🔒 [REVOKE SESSIONS] Semua sesi operator & token aktif dicabut oleh ${operator}. Operator wajib login ulang.`;
      break;
    case 'panic_broadcast':
      alertMessage = `📢 [SYSTEM ALERT] Pengumuman darurat dari Super Admin: ${reason}`;
      break;
    case 'maintenance_toggle':
      alertMessage = `🛑 [MAINTENANCE MODE] Sistem pendaftaran dan akses member dialihkan ke mode pemeliharaan.`;
      break;
  }

  // Broadcast ke Admin dan Member Group jika perlu
  await sendTelegramNotification('@sandekalabot (Admin & Dev Emergency Alert)', alertMessage, 'admin_private');
  
  if (actionType === 'panic_broadcast' || actionType === 'maintenance_toggle') {
    await sendTelegramNotification('@mrssandebot (Member Group)', alertMessage, 'member_group');
  }

  return { success: true, message: alertMessage };
}

export async function claimTicket(ticketId: string, operatorName: string): Promise<void> {
  await logAuditAction('CLAIM_SUPPORT_TICKET', `Ticket #${ticketId} claimed by ${operatorName}`, 'info', operatorName);
  await sendTelegramNotification('@sandekalabot (Admin Channel)', `Support Ticket #${ticketId} claimed by operator ${operatorName}.`, 'admin_private');
  if (isSupabaseConfigured) {
    try {
      await supabase.from('support_tickets').update({ status: 'in_progress', user: operatorName }).eq('id', ticketId);
    } catch (e) {
      console.warn('Supabase claim ticket error:', e);
    }
  }
}

export async function assignTicket(ticketId: string, assigneeName: string, operatorName: string): Promise<void> {
  await logAuditAction('ASSIGN_SUPPORT_TICKET', `Ticket #${ticketId} assigned to ${assigneeName} by ${operatorName}`, 'warn', operatorName);
  await sendTelegramNotification('@sandekalabot (Admin Channel)', `Support Ticket #${ticketId} assigned to ${assigneeName} by ${operatorName}.`, 'admin_private');
  if (isSupabaseConfigured) {
    try {
      await supabase.from('support_tickets').update({ status: 'in_progress', user: assigneeName }).eq('id', ticketId);
    } catch (e) {
      console.warn('Supabase assign ticket error:', e);
    }
  }
}

export async function resolveTicket(ticketId: string, resolutionNotes: string, operatorName: string): Promise<void> {
  await logAuditAction('RESOLVE_SUPPORT_TICKET', `Ticket #${ticketId} resolved: "${resolutionNotes}"`, 'info', operatorName);
  await sendTelegramNotification('@sandekalabot (Admin Channel)', `Support Ticket #${ticketId} resolved by ${operatorName}: ${resolutionNotes}`, 'admin_private');
  if (isSupabaseConfigured) {
    try {
      await supabase.from('support_tickets').update({ status: 'resolved' }).eq('id', ticketId);
    } catch (e) {
      console.warn('Supabase resolve ticket error:', e);
    }
  }
}

/**
 * Link Telegram account with verified Supabase session
 */
export async function linkTelegramAccount(telegramId: string | number, email: string, displayName?: string): Promise<{ success: boolean; user?: any }> {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  if (!supabaseUrl) return { success: true };

  const functionUrl = `${supabaseUrl}/functions/v1/telegram-auth`;
  const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

  try {
    const res = await fetch(functionUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': anonKey,
        'Authorization': `Bearer ${anonKey}`,
      },
      body: JSON.stringify({
        action: 'link_telegram',
        telegram_id: String(telegramId),
        email,
        display_name: displayName
      })
    });
    return await res.json();
  } catch (err) {
    console.warn('linkTelegramAccount request note:', err);
    return { success: false };
  }
}

/**
 * Fetch Claims for User or Admin
 */
export async function fetchUserClaims(telegramId?: string | number): Promise<any[]> {
  if (isSupabaseConfigured) {
    try {
      let query = supabase.from('claims').select('*').order('created_at', { ascending: false });
      if (telegramId) {
        query = query.eq('telegram_user_id', Number(telegramId));
      }
      const { data, error } = await query;
      if (!error && data) return data;
    } catch (e) {
      console.warn('Supabase fetch claims note:', e);
    }
  }
  return [];
}
