import { createClient } from 'npm:@supabase/supabase-js@2';
const URL=Deno.env.get('SUPABASE_URL')!; const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!; const ANON=Deno.env.get('SUPABASE_ANON_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false}}); const authClient=createClient(URL,ANON,{auth:{persistSession:false}});
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const wrap=(r:Response,req:Request)=>{const h=new Headers(r.headers);const configured=Deno.env.get('BACKOFFICE_ORIGIN');const requestOrigin=req.headers.get('origin');const origin=configured||requestOrigin;if(origin)h.set('access-control-allow-origin',origin);h.set('vary','Origin');h.set('access-control-allow-credentials','true');h.set('access-control-allow-headers','authorization,content-type');h.set('access-control-allow-methods','GET,POST,OPTIONS');return new Response(r.body,{status:r.status,headers:h})};
async function actor(req:Request){const h=req.headers.get('authorization');if(!h?.startsWith('Bearer '))return null;const {data,error}=await db.auth.getUser(h.slice(7));if(error||!data.user)return null;const {data:a}=await db.from('dashboard_access').select('id,user_id,role,enabled,expires_at').eq('auth_user_id',data.user.id).maybeSingle();if(!a||!a.enabled||(a.expires_at&&new Date(a.expires_at)<=new Date()))return null;return{authUser:data.user,access:a}}
async function can(a:any,c:string){if(a.access.role==='root')return c==='system.critical';const {data}=await db.from('backoffice_role_capabilities').select('capability_id,backoffice_capabilities!inner(capability)').eq('role',a.access.role).eq('backoffice_capabilities.capability',c).maybeSingle();return !!data}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return wrap(new Response(null,{status:204}),req);try{const p=new URL(req.url).pathname.replace(/^\/functions\/v1\/backoffice-api-v3/,'')||'/';
if(p==='/login'&&req.method==='POST'){const b=await req.json();if(typeof b?.email!=='string'||typeof b?.password!=='string')return wrap(json({error:'invalid_input'},422),req);const{data,error}=await authClient.auth.signInWithPassword({email:b.email.trim(),password:b.password});if(error||!data.session)return wrap(json({error:'invalid_credentials'},401),req);return wrap(json({access_token:data.session.access_token,refresh_token:data.session.refresh_token,expires_at:data.session.expires_at,user:{id:data.user?.id,email:data.user?.email}}),req)}
if(p==='/refresh'&&req.method==='POST'){const b=await req.json();if(typeof b?.refresh_token!=='string'||!b.refresh_token)return wrap(json({error:'invalid_input'},422),req);const{data,error}=await authClient.auth.refreshSession({refresh_token:b.refresh_token});if(error||!data.session)return wrap(json({error:'invalid_refresh_token'},401),req);return wrap(json({access_token:data.session.access_token,refresh_token:data.session.refresh_token,expires_at:data.session.expires_at}),req)}
const a=await actor(req);if(!a)return wrap(json({error:'unauthorized'},401),req);
if(p==='/session'){const{data:user}=await db.from('users').select('id,telegram_id,username,full_name,email,role,status,domain_name,domain_verified,onboarding_status,risk_status,created_at').eq('id',a.access.user_id).maybeSingle();return wrap(json({authenticated:true,actor:{auth_user_id:a.authUser.id,user_id:a.access.user_id,role:a.access.role},user}),req)}
if(p==='/stats'){if(!(await can(a,'users.read_any')))return wrap(json({error:'forbidden'},403),req);const[u,t,pay,w,s,f]=await Promise.all([db.from('users').select('id,domain_verified',{count:'exact'}),db.from('tickets').select('id,status'),db.from('payments').select('id,status'),db.from('web_requests').select('id',{count:'exact',head:true}),db.from('users').select('id',{count:'exact',head:true}).eq('role','super_admin'),db.from('forum_topics').select('id',{count:'exact',head:true})]);const us=u.data||[],ts=t.data||[],ps=pay.data||[];return wrap(json({totalUsers:u.count||us.length,verifiedMembers:us.filter((x:any)=>x.domain_verified).length,pendingTickets:ts.filter((x:any)=>['pending','assigned','waiting_member','in_progress','escalated'].includes(x.status)).length,totalTopics:f.count||0,pendingPayments:ps.filter((x:any)=>x.status==='pending').length,totalWebsites:w.count||0,superAdminCount:s.count||0}),req)}
const routes:any={'/users':['users.read_any','users','id,telegram_id,username,full_name,email,role,status,domain_name,domain_verified,onboarding_status,risk_status,created_at'],'/tickets':['ticket.read_any','tickets','id,ticket_number,user_id,category,priority,status,title,description,assigned_to,created_at,updated_at'],'/payments':['payment.read_any','payments','id,payment_number,user_id,amount,currency,status,proof_path,verification_notes,verified_by,verified_at,created_at'],'/domains':['domain.inspect','web_requests','id,user_id,domain_name,status,health_status,dns_records_json,last_checked_at,created_at,updated_at'],'/audit':['audit.read','audit_logs','id,actor_id,actor_role,action_type,resource_type,resource_id,old_value,new_value,reason,ip_address,created_at'],'/forum-topics':['audit.read','forum_topics','*']};
if(routes[p]){const[cap,table,fields]=routes[p];if(!(await can(a,cap)))return wrap(json({error:'forbidden'},403),req);let q=db.from(table).select(fields).limit(500);q=q.order(table==='tickets'?'updated_at':'created_at',{ascending:false});const{data,error}=await q;if(error)throw error;return wrap(json(data||[]),req)}
if(p==='/notifications'){if(!(await can(a,'audit.read')))return wrap(json({error:'forbidden'},403),req);const{data,error}=await db.from('notifications').select('id,user_id,telegram_id,title,message,type,is_read,created_at').order('created_at',{ascending:false}).limit(200);if(error)throw error;return wrap(json(data||[]),req)}
if(p==='/bot-status'){if(!(await can(a,'bot.simulator')))return wrap(json({error:'forbidden'},403),req);return wrap(json({status:'UNKNOWN',source:'backoffice-api-v3'}),req)}
if(p==='/broadcast'&&req.method==='POST'){if(!(await can(a,'system.critical')))return wrap(json({error:'forbidden'},403),req);const b=await req.json();if(b?.message){await db.from('audit_logs').insert({actor_id:a.authUser.id,actor_role:a.access.role,action_type:'BROADCAST',resource_type:'telegram',new_value:b.message,reason:b.channel||'system broadcast',ip_address:req.headers.get('x-forwarded-for')});return wrap(json({success:true,broadcasted_to:b.channel}),req)}return wrap(json({error:'invalid_payload'},400),req)}
return wrap(json({error:'not_found'},404),req);}catch(e){console.error(e);return wrap(json({error:'internal_error'},500),req)}});